app/src/pages/OnboardingPage.tsx, app/src/pages/ViewSAMLFlowPage.tsx, internal/authservice/service.go, internal/store/auth.go, internal/store/queries/models.go, internal/store/queries/queries.sql.go, internal/store/saml.go, migrate/000025_access_token_sha256.up.sql, sqlc/queries.sql, sqlc/schema.sql
To bring SAML access tokens in line with the security posture typically used by OAuth2 tokens, this PR makes SAML access tokens expire (by wiping them out from the database entirely) on redemption. This PR also makes us store only the SHA256 of SAML access tokens, not their plaintext inputs.
This change also requires some updates to the onboarding page. Some changes to the state management in that page helps us avoid double-redeeming SAML access tokens. It also adds a new UI path to handle the user electing to redeem the token themselves out of band.
While I was touching onboarding, I elected to also change the code snippets to use camel case, in alignment with our docs.
=> Expire SAML access tokens on use, and only store their SHA256

app/.env, app/package-lock.json, app/package.json, app/src/components/LoginGate.tsx, app/src/config.ts, app/src/index.tsx
This PR adds Sentry configuration for the app. We'll do the backend separately.
Two new env vars are needed now: `APP_SENTRY_DSN` and `APP_SENTRY_ENVIRONMENT`. They just get piped into Sentry; better to avoid doing nontrivial things with this baseline layer of observability in our stack.
I set up LoginGate to forward along details about the user when they hit errors, and enabled automatic logging of all failed browser requests.
=> app: Add Sentry

bin/migrate
Similar to #15, but for invoking `migrate`.
=> Add bin/migrate

internal/apiservice/signin.go, internal/store/queries/models.go, internal/store/queries/queries.sql.go, internal/store/sessions.go, migrate/000026_session_token_sha256.up.sql, sqlc/queries.sql, sqlc/schema.sql
This PR has us store only the SHA256 of session tokens. The original value of a session is unchanged in this PR (it's still 32 bytes of randomness), but now lookups all first sha256 the input and check for a match that way.
=> Store only sha256 of session tokens

internal/store/api_keys.go, internal/store/onboarding.go, internal/store/queries/models.go, internal/store/queries/queries.sql.go, migrate/000027_api_key_secret_value_sha256.up.sql, sqlc/queries.sql, sqlc/schema.sql
This PR is akin to #19, but for API keys. API Keys remain a `ssoready_sk_`-prefixed UUID when presented from the API, but only the SHA256 of the underlying UUID is stored. This PR moves API lookups to convert the input to its SHA256 for an equality match.
=> Store only SHA256 of API key tokens

app/src/components/EnvironmentSwitcher.tsx, app/src/components/Page.tsx
Hide the "Overview" link when no environment is selected, and add an empty display treatment in the environment switcher dropdown in that case as well.
=> Make sidebar state clearer when no environment selected

app/src/index.tsx
This PR disables replay session samples for Sentry outside of errors.
=> app: index: disable sentry non-error samples

app/src/App.tsx
This makes the backend return a simpler 401 instead of having to detect that "null" is not, in fact, a valid session token. That in turn makes the Sentry error logs less noisy.
=> app: send empty string when no session token is present

internal/apiservice/signin.go, internal/store/queries/queries.sql.go, internal/store/sessions.go, sqlc/queries.sql
This PR adds an identify call on user signup. A user's name and email, if known, are associated with the analytics user.
This requires an update to the queries because to this point, retrieving a user session only returned the user ID. It now also returns an email and display name.
=> Add identify call on signup

bin/psql
This PR updates `bin/psql` to use IAM-based authentication to connect to database.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html
(`bin/psql` is an internal (i.e. not designed to be useful for the general public) script. It is used by SSOReady to administer the public app.ssoready.com hosted instance.)
=> bin/psql: use iam-based authentication for rds access

app/src/pages/LoginPage.tsx
This PR adds an analytics event for clicking on the `GoogleLogin` button. It also explicitly throws on errors, so that Sentry can log these.
=> LoginPage: add analytics on GoogleLogin

app/src/components/LoginGate.tsx
LoginGate currently "breaks the back button". This PR fixes that. When redirected to `/login` by LoginGate, the back button will go to whatever it was before the user visited a LoginGate-d page.
=> LoginGate: use replace: true when redirecting

.github/workflows/publish-docker-images.yaml
Just api for now. I expect this will not work on the first try, and unfortunately with github actions you kind of have to test on main directly...
=> Add ghcr.io releases for Docker image

.github/workflows/publish-docker-images.yaml
This PR is to fix the failure here: https://github.com/ssoready/ssoready/actions/runs/9689363370/job/26737512093
=> Add permissions block to docker publish-api

.github/workflows/publish-docker-images.yaml
This PR is to fix: https://github.com/ssoready/ssoready/actions/runs/9689486962/job/26737824308
=> docker publish: fix permission issue with id-token

.github/workflows/publish-docker-images.yaml
This PR adds `auth` to the release process already in place for `api`.
=> Add auth to publish-docker-images.yaml

internal/authservice/oauth.go, internal/store/auth.go
This PR has us return a 400 when an OAuth redirect is directed at an organization that doesn't exist.
```console
$ curl http://localhost:8080/v1/oauth/authorize\?client_id=saml_oauth_client_54v5jr37hu34b3nvwmrp0yb3e\&organization_external_id\=123 -v
...
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 28 Jun 2024 16:56:15 GMT
< Content-Length: 128
< 
invalid_argument: bad organization_external_id: organization not found, or organization does not have a primary SAML connection
```
This PR also removes a stray logging line.
=> oauth: authorize: return 400 when organization not found

internal/authservice/oauth.go
The `next-auth@beta` NPM package requires a different subset of OIDC than `next-auth@v4`. In particular, it requires:
1. That the discovery endpoint announces a userinfo endpoint
2. That the token endpoint returns an access_token and token_type endpoint
In our case, these are never really used. Even the beta version still just uses id_token as expected.
=> Add support for next-auth@beta-flavored OIDC

internal/store/queries/queries.sql.go, internal/store/sessions.go, sqlc/queries.sql
This PR has VerifyEmail fail if there's an outstanding verification challenge for the given email. This is in the spirit of reducing the risk of email bombing.
=> VerifyEmail: fail if there's an existing non-expired challenge for email

.github/workflows/publish-docker-images.yaml
This PR moves publishing of ssoready-auth from ghcr.io to docker.io, in anticipation of doing the same for all app, api, and migrate as well.
=> Move publishing of ssoready-auth from ghcr.io to docker.io

.github/workflows/publish-docker-images.yaml
This PR fixes the attestation for auth to follow the docs here: https://github.com/actions/attest-build-provenance
Namely "NOTE: When pushing to Docker Hub, please use "index.docker.io" as the registry portion of the image name."
=> publish-docker-images: auth: fix artifact attestation for docker.io

.github/workflows/publish-docker-images.yaml
This PR moves publishing of api, app, and migrate from ghcr.io to docker.io, following what is already in place for auth.
=> Publish api, app, migrate to docker.io instead of ghcr.io

app/Dockerfile
The app is failing to build in Docker because of a regression in npm:
https://github.com/npm/cli/issues/7657
This PR fixes that issue by pinning app/Dockerfile to the previous version of npm.
=> Use node v22.4 to fix npm regression

app/src/pages/VerifyEmailPage.tsx, cmd/migrate/migrations/000032_app_org_email_logins_disabled.up.sql, cmd/migrate/migrations/000033_email_verification_challenges_complete_time.up.sql, internal/store/queries/models.go, internal/store/queries/queries.sql.go, internal/store/sessions.go, sqlc/queries.sql, sqlc/schema.sql
This PR adds `email_logins_disabled` as an (internal-only) option on `app_organizations`.
When the option is set on an app org, email verifications for users in that app org will fail.
This PR also introduces `complete_time` to `email_verification_challenges`, so that it's possible to do an email login again after completing the previous one; the debouncing logic is updated to ignore completed challenges. This is a ease-of-life feature to demonstrate this feature, because otherwise new email challenge attempts would fail until the previous one expires.
Closes #68.
=> Add `email_logins_disabled` internal option to `app_organizations`

.github/workflows/publish-docker-images.yaml
This PR changes the docker tagging strategy to be SHA-based, so that it's easier for folks to track where they originate from in the repo.
=> Add type=sha to publish-docker-images

app/src/components/DocsLink.tsx, app/src/pages/HomePage.tsx, app/src/pages/ViewEnvironmentPage.tsx, app/src/pages/ViewOrganizationPage.tsx, app/src/pages/ViewSAMLConnectionPage.tsx
This PR adds links to ssoready.com/docs to the headers of tables listing environments, organizations, saml connections, and saml flows.
=> app: Add links to docs for lists of envs, orgs, conns, flows

.github/workflows/publish-docker-images.yaml
This PR has publish-docker-images deploy multi-platform images. At least for now, we'll target only 64-bit Intel and ARM (`linux/amd64` and `linux/arm64`).
Related to #84.
=> publish-docker-images: build for x86, amd64

.github/workflows/publish-docker-images.yaml
This PR fixes the build failures in #85.
Following the documentation in https://docs.docker.com/build/ci/github-actions/multi-platform/, this PR adds the recommended `docker/setup-qemu-action@v3` and `docker/setup-buildx-action@v3` steps for setting up multi-platform builds.
=> publish-docker-images: add setup-buildx, setup-qemu

cmd/api/Dockerfile, cmd/auth/Dockerfile, cmd/migrate/Dockerfile
In #85 and #86, we started publishing cross-platform Docker images. But those packages still always contained linux/arm64 executables.
This PR follows a process Docker documents here: https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/ to enable the Golang builds to produce linux/amd64 artifacts appropriately.
=> api, auth, migrate: update Dockerfile to use BUILDPLATFORM, TARGETOS, TARGETARCH

.github/workflows/deploy-dev-ucarion.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-stage.yaml
In #87, we updated the Dockerfiles for api and auth to expect to be run from a cross-platform build, defaulting to building for the same platform that the build is happening from.
This PR updates our deploy builds for api and auth to explicitly target linux/arm64.
=> deploy-*: use `docker buildx build` to create images

app/src/pages/ListAPIKeysPage.tsx
=> app: ListAPIKeysPage: fix copy for api keys table header

internal/emailaddr/emailaddr.go
This PR has emailaddr convert email domains to lower case. Because in practice the list of allowed domains is itself lower case as well, this has the effect of making the domain whitelist check case-insensitive.
Closes #92.
=> emailaddr: downcase email domains

cmd/auth/task-definition-dev-ucarion.json, cmd/auth/task-definition-prod.json, cmd/auth/task-definition-stage.json
This PR fixes the internal task definitions for auth to use ARM64, not X86_64.
=> auth: fix arch in task definitions

app/src/components/InputTags.tsx
A user discovered that copy-pasting text containing whitespace into the domains list leads to domain whitelist entries containing whitespace. Such entries don't work correctly, and are confusing.
This PR has InputTags trim input values before "adding" them.
=> app: InputTags: trim input before adding to set

app/src/pages/CreateEnvironmentPage.tsx, app/src/pages/ViewEnvironmentPage.tsx, internal/store/environments.go
A customer ran into an issue ultimately caused by putting a leading space in their environment's redirect URL. This PR:
1. Validates that (oauth) redirect URL do not contain spaces
2. Refuses to commit environments whose (oauth) redirect URL does not parse in Go.
There isn't a super easy way to reliably do this URL validate from the frontend; most things in JavaScript-land use WHATWG URLs, but the backend relies on IETF URLs. But this at least improves the user experience for the more common use-case.
=> Improve validation of environment redirect URL formatting

internal/store/scim_directories.go
This PR fixes a regression introduced in #107. I neglected to include this change in the PR.
=> store: scim_directories: stop populating now-removed ClientBearerToken

app/src/components/SecretCopier.tsx, app/src/pages/ListAPIKeysPage.tsx, app/src/pages/ViewSCIMDirectoryPage.tsx
This PR adds a component, `SecretCopier`, for displaying a preview of a secret, without actually revealing it in the UI. Clicking anywhere in a `SecretCopier` copies the actual underlying secret to the clipboard. It's not possible to text in the displayed preview, so it's unlikely a user would accidentally copy the placeholder.
https://github.com/user-attachments/assets/3fde1dfc-9068-4b81-a37e-50f60cc227b3
=> app: Add SecretCopier, use in api keys, oauth clients, scim bearer tokens

app/src/pages/ViewOrganizationPage.tsx
People are finding the current flow for creating setup URLs confusing. Today those URLs get copied to the clipboard with a toast telling you that's what happened.
With this PR, we now present the user with an alert dialog telling them to copy the URL. It's also made clearer that these URLs are secrets.
=> app: ViewOrganizationPage: Show setup urls in an alert dialog

README.md
We've moving to Discord from Slack. This PR adds a link to that discord.
=> README: Add discord link

cmd/adminproxy/fly-prod.toml, cmd/api/task-definition-prod.json
This PR updates the configuration we have for adminproxy. 
It now has the correct name both on the fly.io side and the api side.
=> Fix configuration for adminproxy

app/.idea/app.iml, app/package-lock.json, app/package.json, app/src/components/InfoTooltip.tsx, app/src/components/ui/popover.tsx, app/src/pages/ListAPIKeysPage.tsx, app/src/pages/ViewAPIKeyPage.tsx, app/src/pages/ViewBrandingSettingsPage.tsx, app/src/pages/ViewCustomDomainsPage.tsx, app/src/pages/ViewEnvironmentPage.tsx, app/src/pages/ViewOrganizationPage.tsx, app/src/pages/ViewSAMLConnectionPage.tsx, app/src/pages/ViewSAMLFlowPage.tsx, app/src/pages/ViewSAMLOAuthClientPage.tsx, app/src/pages/ViewSCIMDirectoryPage.tsx, app/src/pages/ViewSCIMGroupPage.tsx, app/src/pages/ViewSCIMUserPage.tsx
This PR passes over all places we display the various entities in SSOReady (envs, orgs, saml conns, etc.) and adds links to docs where appropriate. Every property on objects now has a tooltip that very briefly describes the property and links to the relevant section in the docs.
Showing screenshots of every page would be a bit tedious, so here's a representative example of the new look:
=> app: Add tooltips + links to docs for every property on resources

app/src/pages/ViewSCIMDirectoryPage.tsx, app/src/pages/ViewSCIMRequestPage.tsx, internal/authservice/scim.go, internal/store/auth_scim.go
This PR adds links to docs for SCIM requests. It also has SCIM requests lacking a bearer token entirely, as well as those with a malformed (i.e. not even shaped like the kind SSOReady creates) bearer token.
=> scim: add links to docs in app, give better error messages over http for bad bearer tokens

internal/saml/dsig/dsig.go
This PR removes a stray debugging log in internal/saml/dsig.
=> internal/saml/dsig: remove stray log

internal/authservice/oauth.go, internal/authservice/service.go, internal/statesign/statesign.go, internal/store/auth.go, internal/store/saml.go
This PR simplifies how the `state` query parameter (used in the SAML `/init` endpoint) is encoded, and discontinues use of `RelayState` in SAML AuthnRequest entirely.
The `state` parameter to the `/init` endpoint serves only to keep track of the SAML flow that was created from a user's GetRedirectURL call. Initially, that parameter was also used to keep track of the user's provided `state` and then forwarded along as a SAML RelayState. However, when we later kept track of user-provided `state` directly on SAML flows (to let SSOReady users internally debug their `state`, even for failed SAML flows), it wasn't necessary to keep track of user-provided `state` using query params / RelayState.
This PR takes advantage of this simplification. `statesign` now only keeps track of a `SAMLFlowID`, …
=> auth: simplify state query parameter signing and discontinue internal use of RelayState

internal/store/queries/queries.sql.go, sqlc/queries.sql
This PR fixes the pagination logic for environments, api keys, and OAuth clients. An off-by-one error on these makes us miss the first element of every page after the first.
=> api: Fix pagination of environments, api keys, oauth clients

cmd/migrate/migrations/000050_saml_flow_assertion_id.up.sql, internal/authservice/service.go, internal/saml/samltypes/response.go, internal/saml/validate.go, internal/store/auth.go, internal/store/queries/models.go, internal/store/queries/queries.sql.go, sqlc/queries.sql, sqlc/schema.sql
This PR requires that SAML flows have a unique SAML assertion ID. This defends against replay attacks from IDP-initiated SAML flows.
This uniqueness constraint is implemented at the SAML connection + assertion ID level. It's not clear to me whether this is any less correct than implementing this constraint without the scoping on SAML connection. I opt to do the compound constraint to follow the principle that constraints are never implemented across tenants, unless they're on SSOReady-controlled data.
For context, the SAML specification stipulates:
> Any party that assigns an identifier MUST ensure that there is negligible probability that that party or any other party will accidentally assign the same identifier to a different data object.
This language controls the specified behavior of …
=> Require SAML flows to be unique by SAML <Assertion> ID

admin/bin/prepare-config-json, admin/bin/serve-public, cmd/migrate/migrations/000051_environments_admin_logo_configured.up.sql, internal/apiservice/admin.go, internal/store/admin.go, internal/store/queries/models.go, internal/store/queries/queries.sql.go, sqlc/queries.sql, sqlc/schema.sql
Right now, admin has a dependency on S3 in order to power custom logos. This PR softens that dependency; S3 is only a dependency if you want to use custom logos.
One known caveat in this implementation is that requesting an upload URL marks the environment has having a logo defined. But the upload, which the app immediately uses after requesting the URL, may fail. This isn't a problem for this PR, because 1) we still have handling for GetObject failing, and 2) for self-hosted instances that don't have s3 configured correctly, the attempt to generate a presigned URL will fail beforehand.
Additionally, this PR clarifies/corrects some logs related to running admin and looking for ADMIN_ env vars.
=> Make dependency on S3 optional, for easier self-hosting of admin

internal/saml/dsig/dsig.go, internal/saml/dsig/path.go, internal/saml/samltypes/response.go, internal/saml/validate.go
This PR removes use of encoding/xml from dsig.Verify. This is in service of reducing the risk associated with double-parsing XML documents, and confusion arising from differential XML parser behavior.
Also, this PR has dsig.Verify return the bytes it authenticated. saml.Validate uses those bytes to carry out further business logic.
=> Avoid double-parsing xml documents in dsig, returned validated bytes from dsig.Verify.

package-lock.json, package.json
This PR adds a top-level `npm run dev`.
I don't love using NPM for this -- the top-level project is primarily in Go -- but:
1. We already do so for app and admin, which practically speaking is always running in local dev anyway,
2. Our protoc invocations need top-level NPM already, to generate protoc-gen-es and related targets
3. npm-run-all + dotenv has all we need
=> add top-level `npm run dev`

cmd/api/main.go, cmd/auth/main.go, go.mod, go.sum, internal/slogcorrelation/slogcorrelation.go
This PR adds a correlation_id, scoped to an HTTP request, for all panics and slog-based logs.
=> Add correlation_id for all logs and panics

internal/authservice/scim.go, internal/store/auth_scim.go, internal/store/queries/queries.sql.go, sqlc/queries.sql
This PR adds support for Entra's pattern for updating SCIM user `userName` values. It does so by carrying out a SCIM PATCH request to the user's `userName` attribute.
This PR introduces a new code path that has to take care to make sure to enforce user email domain membership.
=> scim: entra: support PATCHes to userName

internal/authservice/scim.go
This PR fixes a regression introduced in #132. When a user is not found, this PR has scimGetUser return `nil` after setting the response status to 404. Previously, it re-raised the error, leading the scim request logs middleware to treat the error as fatal.
Screenshot of the logs middleware being happy even as a user 404s:
=> authservice: scim: do not treat user 404 as error condition

internal/authservice/scim.go
This PR adds support for Entra's noncompliant practice of sending SCIM PATCHes on groups with an `op` of `Add` (the correct behavior is `add`, but whatever).
=> auth: scim: support PATCH on scim groups with `Add` operation

go.mod, go.sum
This PR updates the dependency on prettyuuid to the latest commit, which provides better error messages.
See: https://github.com/ssoready/prettyuuid/pull/1
=> Update prettyuuid to 285da46

internal/emailaddr/emailaddr.go, internal/emailaddr/emailaddr_test.go
This fixes a bug in SCIM preventing email addresses that contain `-` from being created in SCIM directories.
The `-` character in regex is a reserved character if inside `[]`. A simple escape `\` fixes the logic to what I believe was the original intent.
=> scim: Support '-' in email addresses

internal/store/auth_scim.go
This PR fixes a bug wherein users are marked as deleted on their email being updated.
There was never a good reason we did so; this is a straightforward bug, plain and simple. We overlooked this in QA.
Closes #164.
=> scim: fix user deletion on email PATCHing

internal/authservice/scim.go, internal/scimpatch/scimpatch.go, internal/scimpatch/scimpatch_test.go, internal/store/auth_scim.go
This PR makes two changes to how SCIM user operations work:
1. Introduce scimpatch, which implements SCIM patch semantics, but with exceptions to the spec made to accommodate Entra's noncompliant behavior.
2. The SCIM data model now acts as an intermediate representation (IR). SCIM operations operate on the SCIM data model representation of users, which gets converted to/from the store layer's representation.
The main difficulty here is in accommodating, in a way that makes users get details right by default, two big ways that Entra does not comply with the SCIM specification:
1. The `active` property is supposed to be a boolean, but Entra sets it as the JSON string `"True"` or `"False"` by default.
2. Entra makes up, in some but not all cases, its own syntax for paths to nested fields. …
=> Add scimpatch and use SCIM data model as IR in user scim operations

internal/authservice/scim.go, internal/store/auth_scim.go, internal/store/queries/queries.sql.go, sqlc/queries.sql
This PR adds support for a nonstandard way Entra implements SCIM group/user disassociation: via a PATCH on the group with a `remove` (actually `Remove`) on `members` with a `value`. That `value` is an array with an element whose (inner) `value` is a SCIM user ID.
An example such request:
```
curl -H "Authorization: Bearer ssoready_scim_bearer_token_7ow5vxyzyrbvaege3lvjndp5l" http://localhost:8080/v1/scim/scim_directory_209i1hhe8vls7zrxwmnfvf8rh/Groups/scim_group_93j9z2miz4kgitaqmtycacb47 -X PATCH -d '{"operations": [{"op":"remove","path":"members","value":[{"value":"scim_user_767ja3jcmyly6w7oc0qzh0wnk"}]}]}'
```
=> scim: add support for remove op on members with a value

app/src/pages/ViewEnvironmentPage.tsx
This PR validates that organizations created through the UI do not have leading/trailing whitespace. External ID is often created via copy-paste, so users have noted that whitespace-related problems are easy to have happen.
I've confirmed that not setting an external ID at all continues to work.
=> ViewEnvironmentPage: validate external ID does not have leading/trailing whitespace

app/src/pages/ViewSAMLFlowPage.tsx
It's confusing that we display SAML Flow redeem responses in snake case, whereas the Redeem SAML Access Code API endpoint actually returns camel case over HTTP. This PR has redeem response details be displayed in camel case on SAML flows.
=> ViewSAMLFlowPage: show redeem response details in camel case

cmd/adminproxy/fly-prod.toml, cmd/authproxy/fly-prod.toml
This PR increases the minimum number of machines running for authproxy and adminproxy to 3.
=> authproxy, adminproxy: increase min_machines_running to 3

internal/authservice/log.go, internal/authservice/service.go
This PR adds logs that play nicely with `correlation_id` for the non-sensitive parts of a SAML HTTP request/response. It also adds such logs for the URL that we redirect users to on SAML authentication success.
=> authservice: add correlated logs for SAML http req/res + redirect url

README.md
This PR adds the Go SDK to the badges section and to the links to SDKs in the README.
=> Add links to Go SDK in README

cmd/api/main.go
This PR makes `API_CLOUDFLARE_API_KEY` by instantiating the cloudflare client as nil by default.
Closes #203.
=> api: make API_CLOUDFLARE_API_KEY optional

internal/authservice/scim.go
This PR adds support for SCIM PATCH requests to a user which attempt to remove all properties using a top-level `replace` operation with a value of `{"active": false}`. We deliberately do not support having SCIM users without an email address; few customers are in a place to handle such a user. Currently, such requests fail because the resulting user has no email address, and so fails the email domain check.
To support this sort of deprovisioning strategy, this PR has the SCIM server opt to deactivate the user but keep their email address as-is.
After this PR, these updates work:
```
$ curl -H "authorization: Bearer ..." http://localhost:8080/v1/scim/.../Users/... -X PATCH -d '{"Operations":[{"op":"replace","value":{"active":false}}]}'
```
=> scim: patch users: do not allow removal of userName

internal/authservice/oauth.go, internal/store/auth.go
The logging we do on SAML flows when a saml connection is not properly configured for OAuth does not work when the OAuth flow is done using `?organization_id=...` or `?organization_external_id=...`. This PR fixes that.
Now this request produces the expected error:
```
$ http://localhost:8080/v1/oauth/authorize?client_id=saml_oauth_client_eg9guxp1ygtmb4bsptiujk80m&organization_id=org_8rqbf2kyvxh78mqzhjdpawoml
failed_precondition: environment OAuth redirect URI not configured, see: https://ssoready.com/docs/ssoready-concepts/saml-login-flows#environment-oauth-redirect-uri-not-configured
```
It also correctly produces a failed saml flow:
The same works after configuring the redirect URI, but making the primary saml connection invalid:
```
$ curl …
```
=> auth: fix misconfiguration error logging for oauth flows

internal/authservice/oauth.go, internal/store/saml.go
This PR has us return a 404 with a clear message when double-using, or making up wholesale, a SAML access code.
```
$ curl [...]
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 04 Dec 2024 16:25:12 GMT
< Content-Length: 44
< 
saml access code not found, or already used
```
=> auth: Improve error message on double-use of saml access code in SAML-over-OAuth

internal/store/saml.go
This PR has us return a 404 on failing to find a SAML access code. We already do so for the SAML-over-OAuth flow; this PR updates the main API to have the same behavior.
```
curl -H "content-type: application/json" -H "Authorization: Bearer ssoready_sk_3zbppu18tdzkeke7j4zrggr11" http://localhost:8081/v1/saml/redeem -d '{ "samlAccessCode": "saml_access_code_2pmfho5igl297d65yhnh69gkw" }' -v
*   Trying [::1]:8081...
* connect to ::1 port 8081 failed: Connection refused
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081
> POST /v1/saml/redeem HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/8.4.0
> Accept: */*
> content-type: application/json
> Authorization: Bearer ssoready_sk_3zbppu18tdzkeke7j4zrggr11
> Content-Length: 66
> 
< HTTP/1.1 404 Not Found
< …
```
=> store: saml: return connect.NewError on failing to find saml access code

internal/authservice/oauth.go
This PR has auth return a 400, instead of panicking, on malformed or invalid tokens passed to the userinfo endpoint.
=> auth: 400 instead of panics on invalid tokens passed to oauth userinfo

internal/authservice/service.go, internal/store/auth.go
This PR has auth return a 400 when a SAML assertion meant for one SAML connection is sent to another SAML connection. Previously, we preemptively panicked in this situation.
=> auth: return 400 on saml flow ID / saml connection ID mismatch

internal/authservice/scim.go, internal/store/auth_scim.go, internal/store/queries/queries.sql.go, sqlc/queries.sql, sqlc/schema.sql
This PR allows SCIM clients to filter groups by displayName. This behavior is required by Entra under certain configurations.
```console
$ curl -s -H "Authorization: Bearer ssoready_scim_bearer_token_6jyc3dqv52vo7q8f5m0sp5ucc" http://localhost:8080/v1/scim/scim_directory_3e03jy1zzisw5fdiljwx8xgy5/Groups | jq                          
{
"totalResults": 2,
"itemsPerPage": 2,
"startIndex": 0,
"schemas": [
"urn:ietf:params:scim:schemas:core:2.0:Group"
],
"resources": [
{
"displayName": "asdf",
"id": "scim_group_9nt3cb1j92gqlibjic72533xg"
},
{
"displayName": "foobar",
"id": "scim_group_aa33x9kzeejuhp6jfxzi0tz53"
}
]
}
$ curl -s -H "Authorization: Bearer ssoready_scim_bearer_token_6jyc3dqv52vo7q8f5m0sp5ucc" 'http://localhost:8080/v1/scim/scim_directory_3e03jy1zzisw5fdiljwx8xgy5/Groups?filter=dis …
```
=> auth: scim: allow filtering groups by displayName

internal/authservice/scim.go
Currently error responses in SCIM endpoints are returned as plain text,
which causes them to be filtered out from the request logs in the SSOReady UI.
This makes debugging harder as error details are not visible in the app.
This commit:
- Updates error responses to use SCIM-compliant JSON format
- Sets correct Content-Type header for SCIM responses
- Ensures error responses are properly captured in logs
- Improves error handling for Azure AD/Entra ID integration
Resolves #230
Related to #228
=> fix: format SCIM error responses as JSON for proper logging

internal/authservice/oauth.go
This PR updates the SAML-over-OAuth userinfo endpoint to return `email` and `email_verified` claims that Firebase understands. This saves users from needing to manually copy this information themselves, and is the correct behavior for the majority of Firebase applications.
For example, here's the difference between Firebase's understanding of a user created over SAML-over-OAuth before and after we introduced this change to an existing test Firebase application:
Example of what developers see if they log out the Firebase credentials returned from the login flow:
=> auth: Have userinfo return Firebase-friendly OIDC claims

internal/authservice/service.go, internal/store/auth.go
This PR improves error reporting for the case where an assertion contains a malformed request ID.
=> auth: acs: return 400 on invalid saml request IDs

app/src/pages/ViewSCIMRequestPage.tsx, internal/authservice/scim.go
This PR improves the error that is produced when SCIM clients attempt to PUT a user without a userName. They're now reported in the same way other bad usernames are:
=> Improve error message for SCIM PUT /Users/... without a userName

internal/authservice/service.go, internal/store/auth.go
This PR has us return a 404 with a clear error message when performing an IDP-initiated flow to a well-formed ACS URL for a nonexistent SAML connection.
=> Return clearer 404 when ACSing to incorrect saml connection ID

internal/scimpatch/parser_test.go, internal/scimpatch/scimpatch.go, internal/scimpatch/scimpatch_test.go
This PR incorporates work from #235 and #236. Credit for that work goes to Alex Augustin, Florian Reifschneider, and Christian Nau, all from Omnifact.
This PR adds better support for Entra-flavored SCIM PATCH filter operations. Beyond the work by the authors mentioned above, this PR also adds handling for Entra's behavior with respect to syncing new array fields. Even if an array-valued property (emails, phoneNumbers, etc.) is not present, Entra will still issue filtered SCIM PATCH operations on its value to bring it to the state it expects. This PR accommodates for this request pattern.
In addition, this PR adds further unit testing for scimpatch's parsing of SCIM requests and application of SCIM operations.
=> Improve handling of Entra-flavored SCIM PATCH filter operations

app/src/pages/ViewSCIMDirectoryPage.tsx
This PR adapts #234 to handle 404 cases more gracefully. Credit to @RamNow for the original work this PR is based on.
=> Display 400, 401 SCIM request logs as "Bad request"

internal/authservice/scim.go, internal/authservice/scim_test.go
This PR implements and tests the conversion of SCIM manager references to ensure compatibility with Microsoft Entra (Azure AD). The change converts simple manager ID references to complex references as required by Entra's SCIM implementation.
Implementation Changes:
- Added manager reference conversion in `scimUserToResource` function
- Converts simple manager ID format (`"manager": "manager123"`) to complex format (`"manager": {"value": "manager123"}`)
- Preserves existing complex references
- Maintains backward compatibility with other SCIM providers
Test Coverage:
Added new test file `internal/authservice/scim_test.go` with comprehensive test cases:
- ✅ Simple manager ID conversion to complex reference
- ✅ Complex manager reference preservation
- ✅ Empty manager reference handling
- ✅ …
=> feat: Add Entra-compatible SCIM manager reference conversion with tests

internal/authservice/oauth.go
The current Content-Type for this endpoint (text/plain) interacts poorly with Golang's x/oauth2 package, which attempts to also support form-encoded data.
=> auth: use application/json as content-type for oauth token endpoint

internal/authservice/scim.go, internal/authservice/scim_test.go
Fixes the SCIM user list endpoint to properly support filtering by both `userName` and `email.value` attributes, addressing compatibility issues with different SCIM clients.
- **Enhanced filter regex pattern**: Updated the regular expression in `scimListUsers` from `userName eq "(.*)"` to `(userName|email\.value) eq "(.*)"` to support both filter formats
- **Fixed capture group indexing**: Updated array index from `match[1]` to `match[2]` to correctly extract the email value from the new regex pattern with multiple capture groups
- **Added comprehensive tests**: Created `TestSCIMFilterRegex` to validate the filter parsing logic with various scenarios including:
- `userName eq "email@domain.com"` format
- `email.value eq "email@domain.com"` format  
- Edge cases with special characters in …
=> fix: Support email.value filter in SCIM user list endpoint
